#ifndef _MOTOR_CONFIG_H
#define _MOTOR_CONFIG_H

#include <string.h>
#include <stdint.h>
#include "stm32f4xx_hal_conf.h"

#include "can.h"
#include "robot_config.h"

// 电机接收配置(注意不会影响发送)



#if ROBOT == GOBLIN
// pitch 电机
#define PITCH_MOTOR_CAN_ID 0x11 // pitch轴ID
#define PITCH_MOTOR_CAN CAN2

// 摩擦轮电机
#define LEFT_FRICTION_WHEEL_CAN_ID 0x201  // 摩擦轮ID1(左)
#define RIGHT_FRICTION_WHEEL_CAN_ID 0x202 // 摩擦轮ID2(右)
#define FRICTION_WHEEL_CAN CAN2

// 大Yaw轴电机接收
#define BIG_YAW_MOTOR_CAN_ID 0x10 // big_yaw轴电机，DM8006
#define BIG_YAW_MOTOR_CAN CAN1

// 小Yaw轴电机接收
#define SMALL_YAW_MOTOR_CAN_ID 0x205 // small_yaw轴电机,RM6020
#define SMALL_YAW_MOTOR_CAN CAN2

// 拨弹电机接受代码
#define TOGGLE_MOTOR_CAN_ID 0x204 // 拨弹电机
#define TOGGLE_MOTOR_CAN CAN1

// 底盘通信
#define SEND_TO_CHASSIS_CAN_ID_1 0x150
#define SEND_TO_CHASSIS_CAN_ID_2 0x151
#define GET_FROM_CHASSIS_CAN_ID_1 0x160
#define GET_FROM_CHASSIS_CAN_ID_2 0x161
#define JUDGE_RECEIVE_DATA_CAN_ID_1 0x094
#define JUDGE_RECEIVE_DATA_CAN_ID_2 0x096
#define SEND_TO_GIMBAL_BLOOD_DATA_CAN_ID1 0x097
#define SEND_TO_GIMBAL_RFID_AND_BUFF_DATA_CAN_ID 0x098
#define SEND_TO_GIMBAL_POSITION_DATA_CAN_ID 0x099
#define GET_CHASSIS_SPEED_CAN_ID 0x09A  // 接收底盘速度数据CAN ID
#define CHASSIS_CAN_COMM_CAN_Handlerx hcan1
#define CHASSIS_CAN_COMM_CANx CAN1

// 大yaw通信
#define BIG_YAW_CAN_COMM_CANx CAN2
#define GET_FROM_BIG_YAW_CAN_ID 0x166

//CAN1
// FIFO 0 接收ID
#define CAN1_FIFO0_ID0 SEND_TO_GIMBAL_BLOOD_DATA_CAN_ID1
#define CAN1_FIFO0_ID1 SEND_TO_GIMBAL_RFID_AND_BUFF_DATA_CAN_ID
#define CAN1_FIFO0_ID2 TOGGLE_MOTOR_CAN_ID
#define CAN1_FIFO0_ID3 BIG_YAW_MOTOR_CAN_ID

// FIFO 1 接收ID
#define CAN1_FIFO1_ID0 JUDGE_RECEIVE_DATA_CAN_ID_1
#define CAN1_FIFO1_ID1 GET_FROM_CHASSIS_CAN_ID_1
#define CAN1_FIFO1_ID2 JUDGE_RECEIVE_DATA_CAN_ID_2
#define CAN1_FIFO1_ID3 SEND_TO_GIMBAL_POSITION_DATA_CAN_ID

//CAN2
// FIFO 0 接收ID
#define CAN2_FIFO0_ID0 GET_FROM_BIG_YAW_CAN_ID
#define CAN2_FIFO0_ID1 PITCH_MOTOR_CAN_ID
#define CAN2_FIFO0_ID2 SMALL_YAW_MOTOR_CAN_ID
#define CAN2_FIFO0_ID3 0x000

// FIFO 1 接收ID
#define CAN2_FIFO1_ID0 0x003
#define CAN2_FIFO1_ID1 LEFT_FRICTION_WHEEL_CAN_ID
#define CAN2_FIFO1_ID2 RIGHT_FRICTION_WHEEL_CAN_ID
#define CAN2_FIFO1_ID3 0x000


#elif ROBOT == TIGER

// pitch 电机
#define PITCH_MOTOR_CAN_ID 0x11 // pitch轴ID
#define PITCH_MOTOR_CAN CAN2

// 摩擦轮电机
#define LEFT_FRICTION_WHEEL_CAN_ID 0x201  // 摩擦轮ID1(左)
#define RIGHT_FRICTION_WHEEL_CAN_ID 0x202 // 摩擦轮ID2(右)
#define FRICTION_WHEEL_CAN CAN2

// 大Yaw轴电机接收
#define BIG_YAW_MOTOR_CAN_ID 0x10 // big_yaw轴电机，DM8006
#define BIG_YAW_MOTOR_CAN CAN1

// 小Yaw轴电机接收
#define SMALL_YAW_MOTOR_CAN_ID 0x205 // small_yaw轴电机,RM6020
#define SMALL_YAW_MOTOR_CAN CAN2

// 拨弹电机接受代码
#define TOGGLE_MOTOR_CAN_ID 0x204 // 拨弹电机
#define TOGGLE_MOTOR_CAN CAN1

// 底盘通信
#define SEND_TO_CHASSIS_CAN_ID_1 0x150
#define SEND_TO_CHASSIS_CAN_ID_2 0x151
#define GET_FROM_CHASSIS_CAN_ID_1 0x160
#define GET_FROM_CHASSIS_CAN_ID_2 0x161
#define JUDGE_RECEIVE_DATA_CAN_ID_1 0x094
#define JUDGE_RECEIVE_DATA_CAN_ID_2 0x096
#define SEND_TO_GIMBAL_BLOOD_DATA_CAN_ID1 0x097
#define SEND_TO_GIMBAL_RFID_AND_BUFF_DATA_CAN_ID 0x098
#define SEND_TO_GIMBAL_POSITION_DATA_CAN_ID 0x099
#define GET_CHASSIS_SPEED_CAN_ID 0x09A  // 接收底盘速度数据CAN ID
#define CHASSIS_CAN_COMM_CAN_Handlerx hcan1
#define CHASSIS_CAN_COMM_CANx CAN1

// 大yaw通信
#define BIG_YAW_CAN_COMM_CANx CAN2
#define GET_FROM_BIG_YAW_CAN_ID 0x166

//CAN1
// FIFO 0 接收ID
#define CAN1_FIFO0_ID0 SEND_TO_GIMBAL_BLOOD_DATA_CAN_ID1
#define CAN1_FIFO0_ID1 SEND_TO_GIMBAL_RFID_AND_BUFF_DATA_CAN_ID
#define CAN1_FIFO0_ID2 TOGGLE_MOTOR_CAN_ID
#define CAN1_FIFO0_ID3 BIG_YAW_MOTOR_CAN_ID

// FIFO 1 接收ID
#define CAN1_FIFO1_ID0 JUDGE_RECEIVE_DATA_CAN_ID_1
#define CAN1_FIFO1_ID1 GET_FROM_CHASSIS_CAN_ID_1
#define CAN1_FIFO1_ID2 JUDGE_RECEIVE_DATA_CAN_ID_2
#define CAN1_FIFO1_ID3 SEND_TO_GIMBAL_POSITION_DATA_CAN_ID

//CAN2
// FIFO 0 接收ID
#define CAN2_FIFO0_ID0 GET_FROM_BIG_YAW_CAN_ID
#define CAN2_FIFO0_ID1 PITCH_MOTOR_CAN_ID
#define CAN2_FIFO0_ID2 SMALL_YAW_MOTOR_CAN_ID
#define CAN2_FIFO0_ID3 0x000

// FIFO 1 接收ID
#define CAN2_FIFO1_ID0 0x003
#define CAN2_FIFO1_ID1 LEFT_FRICTION_WHEEL_CAN_ID
#define CAN2_FIFO1_ID2 RIGHT_FRICTION_WHEEL_CAN_ID
#define CAN2_FIFO1_ID3 0x000

#endif

// // 弹舱盖电机
// #define BAY_MOTOR_CAN_ID 0x204
// #define BAY_MOTOR_CAN CAN2

#endif // !_MOTOR_CONFIG_H
